name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy infra
    runs-on: ubuntu-latest

    steps:
    - name: Simple Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: v1.0.4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build Lambda Package
      run: |
        sh scripts/build_lambda_package.sh

    - name: IaC Apply
      run: |
        cd infrastructure
        terraform init
        terraform validate
        terraform plan
        terraform apply -auto-approve